#!/bin/zsh

# shortcut to this dotfiles path is $ZSH
#export ZSH="$HOME/.config/zsh"

# all of the zsh files
typeset -U config_files
config_files=(~/.config/zsh/**/*.zsh)

for file in ${(M)config_files}; do
  source "$file"
done

# ZMV
autoload -U zmv
alias mmv='noglob zmv -W'

# Antigen
source ~/.antigen/antigen.zsh
source ~/.config/zsh/antigen

[[ -s "$HOME/.local/share/marker/marker.sh" ]] && source "$HOME/.local/share/marker/marker.sh"

